name: Upload coverage reports to Codecov

on: [push, pull_request]
jobs:

  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: 3.10
        os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
  	  - uses: codecov/codecov-action@v3


